config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  scope :catalog, only: [:index, :show] do
    # old book-market links format to google & yandex
    get '/:category', to: 'catalogs#show', as: 'catalog'
    get '/:category/:url', to: 'books#show', as: 'book'
  end

  get '/search', to: 'catalogs#search'

  %w(tile big small full).each do |type|
    get "/book_image_#{type}/:image_id", to: "books#image_#{type}", as: "book_image_#{type}"
  end

  scope 'cart', as: :cart do
    root 'cart#show', as: 'root'

    get '/update', to: 'cart#update'

    post ':book_id/minus', to: 'cart#minus', as: :minus
    post ':book_id/plus', to: 'cart#plus', as: :plus
    post ':book_id/add', to: 'cart#add', as: :add
    post ':book_id/del', to: 'cart#del', as: :del
  end

  # TODO order scope
  get '/order', to: 'orders#order'
  get '/delivery_info', to: 'orders#delivery_info'
  post '/delivery_info', to: 'orders#make_order', as: 'make_order'
  get '/thankyou', to: 'orders#thank_you'

  # scope 'order', as: :order do
  #   root 'order#show'
  #
  #   get '/delivery', to: 'orders#delivery'
  #   post '/create', to: 'orders#create'
  #   get '/thankyou', to: 'orders#thank_you'
  # end

  # TODO add pages routes

  namespace :control_panel, as: 'cp', path: 'cp' do
    root 'dashboard#index', as: 'root'

    resources :categories, :orders, :clients

    resources :books do
      get :images
      patch :image_upload
      get :image_delete
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord

  belongs_to :parent, class_name: 'Category', optional: true

  has_many :subcategories, class_name: 'Category', foreign_key: :parent_id

  validates :url, presence: true, uniqueness: true, length: (5..100)
  validates :name, presence: true, length: (5..250)

  scope :catalogs, -> { where(parent: nil).includes(:subcategories) }

  # TODO find usages. add test. and rename?
  scope :only_categories, -> { where('parent_id is not null') }

end

app/controllers/control_panel/books_controller.rb
class ControlPanel::BooksController < ApplicationController

  layout 'control_panel'

  def index
    @books = Book.order(id: :desc).first(10)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params(:url)

    if @book.save
      redirect_to(controller: '/control_panel/books', action: 'edit', id: @book)
    else
      render 'new'
    end
  end

  def show
    @book = Book.find params[:id]
  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    @book = Book.find params[:id]
    @book.update_attributes(book_params)

    redirect_to(controller: '/control_panel/books', action: 'show', id: @book)
  end

  def images
    @book = Book.find params[:book_id]
    render 'images', layout: false
  end

  def image_upload
    @book = Book.find params[:book_id]
    image = @book.images.build
    image.image = params[:file]

    if @book.save
      render json: :success
    else
      render json: {error: @book.errors[:file]}, status: 422
    end
  end

  def image_delete
    @book = Book.find params[:book_id]
    if params[:img].present?
      @book.images.find(params[:img]).destroy
    end

    render 'edit'
  end

  private

  def book_params(*args)
    params.require(:book).permit(fields << args)
  end

  def fields
    [:text, :name, :price, :category_id, :available, image_attributes: :image]
  end

end

app/controllers/control_panel/categories_controller.rb
class ControlPanel::CategoriesController < ApplicationController

  layout 'control_panel'

  def index
    @categories = Category.includes(:parent).all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params(:url)

    if @category.save
      redirect_to cp_categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find params[:id]
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    @category.update! category_params

    redirect_to cp_categories_path
  end

  private

  def category_params(*args)
    params.require(:category).permit(fields << args)
  end

  def fields
    [:name, :parent_id]
  end

end

app/controllers/control_panel/clients_controller.rb
class ControlPanel::ClientsController < ApplicationController

  layout 'control_panel'

  before_action :find_client, only: [:show, :edit]

  def index
    @clients = Client.order(id: :desc)
    @clients_count = {all: Client.count}
  end

  def new
  end

  def show
  end

  def edit
  end

  private

  def find_client
    @client = Client.find params[:id]
  end

end

app/controllers/control_panel/dashboard_controller.rb
class ControlPanel::DashboardController < ApplicationController

  layout 'control_panel'

  def index
    # TODO orders list
  end

end

app/controllers/control_panel/orders_controller.rb
class ControlPanel::OrdersController < ApplicationController

  layout 'control_panel'

  before_action :find_order, only: [:show, :edit, :update]

  def index
    @orders = Order.includes(:status).order(id: :desc)
    @orders_count = {all: Order.count}
  end

  def new
    @order = Order.new
    @order.books.build
  end

  def create
    @order = Order.new order_params(:url)
    render action: @order.save ? :show : :new
  end

  def show
  end

  def edit
    @order.books.build
  end

  def update
    @order.update order_params
    render action: @order.save ? :show : :edit
  end

  private

  def find_order
    @order = Order.find params[:id]
  end

  def order_params(*args)
    params.require(:order).permit(fields << args)
  end

  def fields
    [:status_id, books_attributes: [:_destroy, :id, :book_id, :quantity, :price]]
  end

end

app/views/control_panel/categories/_form.haml
.row
  .input-field.col.s12
    %i.material-icons.prefix reorder
    = f.collection_select :parent_id, Category.all, :id, :name
    = f.label :parent_id, 'Из категории', class: 'icon_prefix'

  .input-field.col.s12
    %i.material-icons.prefix mode_edit
    = f.text_field :name, id: 'icon_prefix', class: 'validate'
    = f.label :name, 'Название', class: 'icon_prefix'

  .input-field.col.s12
    %i.material-icons.prefix http
    = f.text_field :url, id: 'icon_prefix', class: 'validate'
    = f.label :url, 'Путь URL', class: 'icon_prefix'

= f.submit class: 'btn waves-effect waves-light'

:javascript
  $(document).ready(function() {
    $('select').material_select();
    Materialize.updateTextFields();
  });

app/views/control_panel/categories/edit.haml
.row
  .col.s12
    %h3 Редактировать категорию

  = form_for @category, url: cp_category_path(@category), id: 'category_form' do |f|
    = render 'form', f: f

app/views/control_panel/categories/index.haml
.row
  .col.s12.m6.l4
    = render '/control_panel/shared/tile', link: new_cp_category_path, title: '+', text: 'Добавить'
  .col.s12.m6.l4
    = render '/control_panel/shared/tile', link: '', title: Category.catalogs.size, text: 'Каталогов'
  .col.s12.m6.l4
    = render '/control_panel/shared/tile', link: '', title: @categories.size, text: 'Всего'

.row
  .col.s12
    - if @categories.any?
      %table.stripped
        %thead
          %tr
            %td Название
            %td Путь URL - уникальный
            %td Родительский
            %td Действие

        - @categories.each do |category|
          %tr
            %td= link_to category.name, cp_category_path(category)
            %td= category.url
            %td= category.parent ? category.parent.name : 'Catalog'
            %td
              = link_to cp_category_path(category) do
                %i.material-icons.small visibility
              = link_to edit_cp_category_path(category) do
                %i.material-icons.small edit

app/views/control_panel/categories/new.haml
.row
  .col.s12
    %h3 Добавить новую категорию

  = form_for @category, url: cp_categories_path, id: 'category_form' do |f|
    = render 'form', f: f

app/views/control_panel/categories/show.haml
.info-box
  .info-box-header Category Info

  .info-box-content
    .info_line
      .info_line-title Name
      .info_line-text= @category.name

    .info_line
      .info_line-title URL
      .info_line-text= @category.url

    .info_line
      .info_line-title Parent
      .info_line-text
        - if @category.parent
          = link_to @category.parent.name, cp_category_path(@category.parent)
        - else
          Main Catalog

.info-box
  .info-box-header Subcategories

  .info-box-content
    - if @category.subcategories.any?
      .info_line
        %ul
          - @category.subcategories.each do |category|
            %li= link_to category.name, cp_category_path(category)
    - else
      %p No subcategories