config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  scope :catalog, only: [:index, :show] do
    # old book-market links format to google & yandex
    get '/:category', to: 'catalogs#show', as: 'catalog'
    get '/:category/:url', to: 'books#show', as: 'book'
  end

  get '/search', to: 'catalogs#search'

  %w(tile big small full).each do |type|
    get "/book_image_#{type}/:image_id", to: "books#image_#{type}", as: "book_image_#{type}"
  end

  scope 'cart', as: :cart do
    root 'cart#show', as: 'root'

    get '/update', to: 'cart#update'

    post ':book_id/minus', to: 'cart#minus', as: :minus
    post ':book_id/plus', to: 'cart#plus', as: :plus
    post ':book_id/add', to: 'cart#add', as: :add
    post ':book_id/del', to: 'cart#del', as: :del
  end

  # TODO order scope
  get '/order', to: 'orders#order'
  get '/delivery_info', to: 'orders#delivery_info'
  post '/delivery_info', to: 'orders#make_order', as: 'make_order'
  get '/thankyou', to: 'orders#thank_you'

  # scope 'order', as: :order do
  #   root 'order#show'
  #
  #   get '/delivery', to: 'orders#delivery'
  #   post '/create', to: 'orders#create'
  #   get '/thankyou', to: 'orders#thank_you'
  # end

  # TODO add pages routes

  namespace :control_panel, as: 'cp', path: 'cp' do
    root 'dashboard#index', as: 'root'

    resources :categories, :orders, :clients

    resources :books do
      get :images
      patch :image_upload
      get :image_delete
    end
  end

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :category

  has_many :images, class_name: 'BookImage'
  accepts_nested_attributes_for :images, allow_destroy: true

  scope :from_catalog, ->(catalog) { where(category_id: catalog.subcategories.pluck(:id) << catalog.id) }

  validates :url, presence: true, uniqueness: true, length: (5..100)
  validates :name, presence: true, length: (5..250)
  validates :text, presence: true, length: {minimum: 5}
  validates :price, presence: true, numericality: {greater_than: 0}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find_by(url: params[:url])
  end

  def image_full
    send_image BookImage.find(params[:image_id])
  end

  def image_big
    send_image BookImage.find(params[:image_id]), :big
  end

  def image_tile
    send_image BookImage.find(params[:image_id]), :tile
  end

  def image_small
    send_image BookImage.find(params[:image_id]), :small
  end

  private

  def send_image(image, type = nil)
    send_file (type ? image.image.versions[type].path : image.image.path), type: 'image/jpeg', disposition: 'inline'
  end

end

app/controllers/control_panel/books_controller.rb
class ControlPanel::BooksController < ApplicationController

  layout 'control_panel'

  def index
    @books = Book.order(id: :desc).first(10)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params(:url)

    if @book.save
      redirect_to(controller: '/control_panel/books', action: 'edit', id: @book)
    else
      render 'new'
    end
  end

  def show
    @book = Book.find params[:id]
  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    @book = Book.find params[:id]
    @book.update_attributes(book_params)

    redirect_to(controller: '/control_panel/books', action: 'show', id: @book)
  end

  def images
    @book = Book.find params[:book_id]
    render 'images', layout: false
  end

  def image_upload
    @book = Book.find params[:book_id]
    image = @book.images.build
    image.image = params[:file]

    if @book.save
      render json: :success
    else
      render json: {error: @book.errors[:file]}, status: 422
    end
  end

  def image_delete
    @book = Book.find params[:book_id]
    if params[:img].present?
      @book.images.find(params[:img]).destroy
    end

    render 'edit'
  end

  private

  def book_params(*args)
    params.require(:book).permit(fields << args)
  end

  def fields
    [:text, :name, :price, :category_id, :available, image_attributes: :image]
  end

end

app/controllers/control_panel/categories_controller.rb
class ControlPanel::CategoriesController < ApplicationController

  layout 'control_panel'

  def index
    @categories = Category.includes(:parent).all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params(:url)

    if @category.save
      redirect_to cp_categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find params[:id]
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    @category.update! category_params

    redirect_to cp_categories_path
  end

  private

  def category_params(*args)
    params.require(:category).permit(fields << args)
  end

  def fields
    [:name, :parent_id]
  end

end

app/controllers/control_panel/clients_controller.rb
class ControlPanel::ClientsController < ApplicationController

  layout 'control_panel'

  before_action :find_client, only: [:show, :edit]

  def index
    @clients = Client.order(id: :desc)
    @clients_count = {all: Client.count}
  end

  def new
  end

  def show
  end

  def edit
  end

  private

  def find_client
    @client = Client.find params[:id]
  end

end

app/controllers/control_panel/dashboard_controller.rb
class ControlPanel::DashboardController < ApplicationController

  layout 'control_panel'

  def index
    # TODO orders list
  end

end

app/controllers/control_panel/orders_controller.rb
class ControlPanel::OrdersController < ApplicationController

  layout 'control_panel'

  before_action :find_order, only: [:show, :edit, :update]

  def index
    @orders = Order.includes(:status).order(id: :desc)
    @orders_count = {all: Order.count}
  end

  def new
    @order = Order.new
    @order.books.build
  end

  def create
    @order = Order.new order_params(:url)
    render action: @order.save ? :show : :new
  end

  def show
  end

  def edit
    @order.books.build
  end

  def update
    @order.update order_params
    render action: @order.save ? :show : :edit
  end

  private

  def find_order
    @order = Order.find params[:id]
  end

  def order_params(*args)
    params.require(:order).permit(fields << args)
  end

  def fields
    [:status_id, books_attributes: [:_destroy, :id, :book_id, :quantity, :price]]
  end

end

app/views/control_panel/books/_big_image.haml
.big_img
  - if @book.images.any?
    %a#main-img-link.gallery2{href: @book.images[0].image_url, rel: 'group'}
      %img#main-img{src: @book.images[0].image_url(:big)}

app/views/control_panel/books/_book_images.haml
- @book.images.each do |image|
  = image_tag book_image_tile_path image
  = link_to 'del', "#{cp_book_image_delete_path(@book)}?img=#{image.id}"

app/views/control_panel/books/_buy.haml
#book_buy.book_cell
  %span.book_buy_price
    = "#{@book.price} #{t(:uah)}"
  %a.book_buy_button{data: {id: @book.id}}
    = t('book.to_cart')
  #send.book_buy_available
    = t('book.in_stock')

app/views/control_panel/books/_form.haml
.row
  .input-field.col.s12
    %i.material-icons.prefix reorder
    = f.collection_select :category_id, Category.only_categories, :id, :name
    = f.label :category_id, 'Из категории', class: 'icon_prefix'

  .input-field.col.s12
    %i.material-icons.prefix mode_edit
    = f.text_field :name, id: 'icon_prefix', class: 'validate'
    = f.label :name, 'Название', class: 'icon_prefix'

  .input-field.col.s12
    %i.material-icons.prefix http
    = f.text_field :url, id: 'icon_prefix', class: 'validate'
    = f.label :url, 'Путь URL', class: 'icon_prefix'

  .input-field.col.s6.m4.l3
    %i.material-icons.prefix attach_money
    = f.text_field :price, id: 'icon_prefix', class: 'validate'
    = f.label :price, 'Цена', class: 'icon_prefix'

  = f.label :available, 'Наличие'
  .switch
    %label
      Отсутствует
      = f.check_box :available
      %span.lever
      В наличии

  .input-field.col.s12
    %i.material-icons.prefix description
    = f.text_area :text, id: 'icon_prefix', class: 'materialize-textarea'
    = f.label :text, 'Содержание', class: 'icon_prefix'

= f.submit class: 'btn waves-effect waves-light'

:javascript
  $(document).ready(function() {
    $('select').material_select();
    Materialize.updateTextFields();
  });

app/views/control_panel/books/_info.haml
.book_info.book_cell
  %ul.book_info_param
    %li
      .book_info_param-left
        = t('book.publisher')
      .book_info_param-right
        = @book.try(:annotation) || '-'
    %li
      .book_info_param-left
        = t('book.cover')
      .book_info_param-right
        = @book.try(:annotation) || '-'
    %li
      .book_info_param-left
        = t('book.dimensions')
      .book_info_param-right
        = @book.try(:annotation) || '-'
    %li
      .book_info_param-left
        = t('book.page_count')
      .book_info_param-right
        = @book.try(:annotation) || '-'

  %h3.book_info_annotation
    = @book.try(:annotation) || '-'
  %pre.book_info_description
    = @book.text

app/views/control_panel/books/_small_images.haml
%ul
  - if @book.images.any?
    - @book.images.each do |image|
      - link = image.file_exist? ? image.image_url(:tile) : '/img/wm/watermark_220_10b.png'
      %li.small_img
        = link_to link, rel: 'group' do
          = image_tag link

app/views/control_panel/books/edit.haml
.row
  .col.s12
    %h3 Редактировать книгу

  = form_for @book, url: cp_book_path(@book), id: 'book_form' do |f|
    = render 'form', f: f

-# TODO REVIEW code form_for
= form_for @book, url: cp_book_image_upload_path(@book), html: { multipart: true, class: 'dropzone', id: 'dropzone_upload'}, data: {url: cp_book_images_path(@book)}  do |f|
  .fallback
    = f.file_field :image
    = f.submit 'Upload'

#book_images
  = render 'book_images'

:javascript
  $(document).ready(function(){
    Dropzone.autoDiscover = false;

    $("#dropzone_upload").dropzone({
        maxFilesize: 10,

        success: function(file, response){
            $(file.previewTemplate).find('.dz-remove').attr('id', response.fileID);
            $(file.previewElement).addClass("dz-success");

            $.ajax({
              url : $("#dropzone_upload").data('url'),
              dataType : "script"
            });
        },

        removedfile: function(file){
            var id = $(file.previewTemplate).find('.dz-remove').attr('id');

            // make a DELETE ajax request to delete the file
            $.ajax({
                type: 'DELETE',
                url: '/uploads/' + id,
                success: function(data){
                    console.log(data.message);
                }
            });
        }

    });
  });

app/views/control_panel/books/index.haml
.row
  .col.s12.m6.l4
    = render '/control_panel/shared/tile', link: new_cp_book_path, title: '+', text: 'Добавить'
  .col.s12.m6.l4
    = render '/control_panel/shared/tile', link: '', title: 5, text: 'В наличии'
  .col.s12.m6.l4
    = render '/control_panel/shared/tile', link: '', title: Book.all.size, text: 'Всего'

.row
  .col.s12
    - if @books.any?
      %table.stripped
        %thead
          %tr
            %td ID
            %td Название
            %td Путь URL - уникальный
            %td Цена
            %td Действие

        - @books.each do |book|
          %tr
            %td
              %span{id: "book_#{book.id}"}= book.id
            %td= book.name
            %td= book.url
            %td #{book.price} грн
            %td
              = link_to 'Изменить', edit_cp_book_path(book)

app/views/control_panel/books/new.haml
.row
  .col.s12
    %h3 Добавить новую книгу

  = form_for @book, url: cp_books_path, id: 'book_form', class: 'col s12' do |f|
    = render 'form', f: f

app/views/control_panel/books/show.haml
-#- page_heading(@book.name)

%h1.main_title
  = @book.name

#main
  .book_container
    .book_images.book_cell#gallery
      = render 'big_image'
      = render 'small_images'

    = render 'info'
    = render 'buy'