config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  scope :catalog, only: [:index, :show] do
    # old book-market links format to google & yandex
    get '/:category', to: 'catalogs#show', as: 'catalog'
    get '/:category/:url', to: 'books#show', as: 'book'
  end

  get '/search', to: 'catalogs#search'

  %w(tile big small full).each do |type|
    get "/book_image_#{type}/:image_id", to: "books#image_#{type}", as: "book_image_#{type}"
  end

  scope 'cart', as: :cart do
    root 'cart#show', as: 'root'

    get '/update', to: 'cart#update'

    post ':book_id/minus', to: 'cart#minus', as: :minus
    post ':book_id/plus', to: 'cart#plus', as: :plus
    post ':book_id/add', to: 'cart#add', as: :add
    post ':book_id/del', to: 'cart#del', as: :del
  end

  # TODO order scope
  get '/order', to: 'orders#order'
  get '/delivery_info', to: 'orders#delivery_info'
  post '/delivery_info', to: 'orders#make_order', as: 'make_order'
  get '/thankyou', to: 'orders#thank_you'

  # scope 'order', as: :order do
  #   root 'order#show'
  #
  #   get '/delivery', to: 'orders#delivery'
  #   post '/create', to: 'orders#create'
  #   get '/thankyou', to: 'orders#thank_you'
  # end

  # TODO add pages routes

  namespace :control_panel, as: 'cp', path: 'cp' do
    root 'dashboard#index', as: 'root'

    resources :categories, :orders, :clients

    resources :books do
      get :images
      patch :image_upload
      get :image_delete
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :status, class_name: 'OrderStatus'

  belongs_to :client
  accepts_nested_attributes_for :client

  has_many :books, class_name: 'OrderBook'
  accepts_nested_attributes_for :books, allow_destroy: true

  # validates_presence_of :status
  validates_presence_of :books
  # validates :total, numericality: {integer_only: true, greater_than: 0}, allow_blank: false

  before_validation :remove_empty

  def remove_empty
    self.books.each { |b| b.destroy! unless b.book_id }
  end

  def add_books(order_books)
    order_books.each do |order_book|
      self.books.build(
          book: order_book[:book],
          quantity: order_book[:qty],
          price: order_book[:book].price
      )
    end

    # REVIEW recalculate before save or after every book changes?
    recalculate_total
  end

  def recalculate_total
    self.total = books.inject(0) { |sum, order_book| sum += order_book.quantity * order_book.price }
  end

  private

  def set_status(status)
    self.status = OrderStatus.find_by_symbol(status)
  end

end

app/controllers/control_panel/orders_controller.rb
class ControlPanel::OrdersController < ApplicationController

  layout 'control_panel'

  before_action :find_order, only: [:show, :edit, :update]

  def index
    @orders = Order.includes(:status).order(id: :desc)
    @orders_count = {all: Order.count}
  end

  def new
    @order = Order.new
    @order.books.build
  end

  def create
    @order = Order.new order_params(:url)
    render action: @order.save ? :show : :new
  end

  def show
  end

  def edit
    @order.books.build
  end

  def update
    @order.update order_params
    render action: @order.save ? :show : :edit
  end

  private

  def find_order
    @order = Order.find params[:id]
  end

  def order_params(*args)
    params.require(:order).permit(fields << args)
  end

  def fields
    [:status_id, books_attributes: [:_destroy, :id, :book_id, :quantity, :price]]
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  # TODO rename create
  def order
    if session[:cart].is_a?(Hash) && session[:cart].any?
      @order = Order.new(session: session.id)
      @order.add_books order_books

      if @order.save
        redirect_to(controller: :orders, action: :delivery_info, total: @order.total.to_f)
      else
        redirect_to(controller: :orders, action: :order)
      end

    else
      redirect_to(controller: :orders, action: :order)
    end
    # TODO order params (name, address, payment etc)
  end

  # TODO rename to ordering client delivery info
  def delivery_info
    # TODO create client or find

    # TODO assigning client to order ans save

    @client = Client.new(
        name: params[:name],
        phone: params[:phone],
        address: params[:address],
        delivery_id: params[:delivery_id],
        payment_id: params[:payment_id],
        notes: params[:notes],
        email: params[:email]
    )
    @order_total = params[:total]
  end

  # TODO rename to order
  def make_order
    @order = Order.find_by_session session.id

    @client = @order.build_client(
        name: params[:client][:name],
        phone: params[:client][:phone],
        address: params[:client][:address],
        delivery_id: params[:client][:delivery_id],
        payment_id: params[:client][:payment_id],
        notes: params[:client][:notes],
        email: params[:client][:email]
    )

    if @order.save
      redirect_to(controller: :orders, action: :thank_you)
    else
      redirect_to(controller: :orders, action: :delivery_info, params: params[:client])
    end
  end

  def thank_you
    @order = Order.find_by_session session.id
    session[:cart] = []
    # TODO order complete
  end

  private

  def order_books
    Book.where(id: session[:cart].map { |id, _| id }).map { |book| {book: book, qty: session[:cart][book.id.to_s]} }
  end

end

app/views/orders/delivery_info.haml
.row
  .col.s12
    - if !@client.valid? && @client.errors.any?
      - @client.errors.each do |error, text|
        %p #{error}:
        %span.text-red= text

.row
  .col.l8
    = form_for @client, {url: delivery_info_path(@client), id: 'order_form', class: 'form-container'} do |client|

      .form_group
        = client.text_field :name, class: 'form_text'
        = client.label :name, 'Имя и фамилия: ', class: 'form-label'

      .form_group
        = client.text_field :phone, class: 'form_text'
        = client.label :phone, 'Мобильный тел.: ', class: 'form-label'

      .form_group
        = client.text_field :address, class: 'form_text'
        = client.label :address, 'Адрес доставки: ', class: 'form-label'

      .form_group
        = client.collection_select :delivery_id, DeliveryType.all, :id, :name, {:prompt=>true}, {class: 'form_select'}
        = client.label :delivery_id, 'Доставка: ', class: 'form-label'

      .form_group
        = client.collection_select :payment_id, PaymentType.all, :id, :name, {:prompt=>true}, {class: 'form_select'}
        = client.label :payment_id, 'Payment: ', class: 'form-label'

      .form_group
        = client.text_field :notes, class: 'form_text'
        = client.label :notes, 'Комментарий к заказу: ', class: 'form-label'

      .form_group
        = client.text_field :email, class: 'form_text'
        = client.label :email, 'E-mail адрес: ', class: 'form-label'

      = client.submit class: 'btn waves-effect waves-light'

app/views/orders/order.haml
%h1 Orders

app/views/orders/thank_you.haml
%h1 Заказ успешно оформлен

%p Менеджер позвонит Вам на номер #{@order.client.try(:phone)} в ближайшее время

- if @order.client.email.present?
  %p письмо отправлено на почту #{@order.client.email}
- else
  %p письмо НЕ БЫЛО отправлено, потому что почта не указана

%strong Спасибо за покупки!