config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  scope :catalog, only: [:index, :show] do
    # old book-market links format to google & yandex
    get '/:category', to: 'catalogs#show', as: 'catalog'
    get '/:category/:url', to: 'books#show', as: 'book'
  end

  get '/search', to: 'catalogs#search'

  %w(tile big small full).each do |type|
    get "/book_image_#{type}/:image_id", to: "books#image_#{type}", as: "book_image_#{type}"
  end

  scope 'cart', as: :cart do
    root 'cart#show', as: 'root'

    get '/update', to: 'cart#update'

    post ':book_id/minus', to: 'cart#minus', as: :minus
    post ':book_id/plus', to: 'cart#plus', as: :plus
    post ':book_id/add', to: 'cart#add', as: :add
    post ':book_id/del', to: 'cart#del', as: :del
  end

  # TODO order scope
  get '/order', to: 'orders#order'
  get '/delivery_info', to: 'orders#delivery_info'
  post '/delivery_info', to: 'orders#make_order', as: 'make_order'
  get '/thankyou', to: 'orders#thank_you'

  # scope 'order', as: :order do
  #   root 'order#show'
  #
  #   get '/delivery', to: 'orders#delivery'
  #   post '/create', to: 'orders#create'
  #   get '/thankyou', to: 'orders#thank_you'
  # end

  # TODO add pages routes

  namespace :control_panel, as: 'cp', path: 'cp' do
    root 'dashboard#index', as: 'root'

    resources :categories, :orders, :clients

    resources :books do
      get :images
      patch :image_upload
      get :image_delete
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :status, class_name: 'OrderStatus'

  belongs_to :client
  accepts_nested_attributes_for :client

  has_many :books, class_name: 'OrderBook'
  accepts_nested_attributes_for :books, allow_destroy: true

  # validates_presence_of :status
  validates_presence_of :books
  # validates :total, numericality: {integer_only: true, greater_than: 0}, allow_blank: false

  before_validation :remove_empty

  def remove_empty
    self.books.each { |b| b.destroy! unless b.book_id }
  end

  def add_books(order_books)
    order_books.each do |order_book|
      self.books.build(
          book: order_book[:book],
          quantity: order_book[:qty],
          price: order_book[:book].price
      )
    end

    # REVIEW recalculate before save or after every book changes?
    recalculate_total
  end

  def recalculate_total
    self.total = books.inject(0) { |sum, order_book| sum += order_book.quantity * order_book.price }
  end

  private

  def set_status(status)
    self.status = OrderStatus.find_by_symbol(status)
  end

end

app/controllers/control_panel/books_controller.rb
class ControlPanel::BooksController < ApplicationController

  layout 'control_panel'

  def index
    @books = Book.order(id: :desc).first(10)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params(:url)

    if @book.save
      redirect_to(controller: '/control_panel/books', action: 'edit', id: @book)
    else
      render 'new'
    end
  end

  def show
    @book = Book.find params[:id]
  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    @book = Book.find params[:id]
    @book.update_attributes(book_params)

    redirect_to(controller: '/control_panel/books', action: 'show', id: @book)
  end

  def images
    @book = Book.find params[:book_id]
    render 'images', layout: false
  end

  def image_upload
    @book = Book.find params[:book_id]
    image = @book.images.build
    image.image = params[:file]

    if @book.save
      render json: :success
    else
      render json: {error: @book.errors[:file]}, status: 422
    end
  end

  def image_delete
    @book = Book.find params[:book_id]
    if params[:img].present?
      @book.images.find(params[:img]).destroy
    end

    render 'edit'
  end

  private

  def book_params(*args)
    params.require(:book).permit(fields << args)
  end

  def fields
    [:text, :name, :price, :category_id, :available, image_attributes: :image]
  end

end

app/controllers/control_panel/categories_controller.rb
class ControlPanel::CategoriesController < ApplicationController

  layout 'control_panel'

  def index
    @categories = Category.includes(:parent).all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params(:url)

    if @category.save
      redirect_to cp_categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find params[:id]
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    @category.update! category_params

    redirect_to cp_categories_path
  end

  private

  def category_params(*args)
    params.require(:category).permit(fields << args)
  end

  def fields
    [:name, :parent_id]
  end

end

app/controllers/control_panel/clients_controller.rb
class ControlPanel::ClientsController < ApplicationController

  layout 'control_panel'

  before_action :find_client, only: [:show, :edit]

  def index
    @clients = Client.order(id: :desc)
    @clients_count = {all: Client.count}
  end

  def new
  end

  def show
  end

  def edit
  end

  private

  def find_client
    @client = Client.find params[:id]
  end

end

app/controllers/control_panel/dashboard_controller.rb
class ControlPanel::DashboardController < ApplicationController

  layout 'control_panel'

  def index
    # TODO orders list
  end

end

app/controllers/control_panel/orders_controller.rb
class ControlPanel::OrdersController < ApplicationController

  layout 'control_panel'

  before_action :find_order, only: [:show, :edit, :update]

  def index
    @orders = Order.includes(:status).order(id: :desc)
    @orders_count = {all: Order.count}
  end

  def new
    @order = Order.new
    @order.books.build
  end

  def create
    @order = Order.new order_params(:url)
    render action: @order.save ? :show : :new
  end

  def show
  end

  def edit
    @order.books.build
  end

  def update
    @order.update order_params
    render action: @order.save ? :show : :edit
  end

  private

  def find_order
    @order = Order.find params[:id]
  end

  def order_params(*args)
    params.require(:order).permit(fields << args)
  end

  def fields
    [:status_id, books_attributes: [:_destroy, :id, :book_id, :quantity, :price]]
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  # TODO rename create
  def order
    if session[:cart].is_a?(Hash) && session[:cart].any?
      @order = Order.new(session: session.id)
      @order.add_books order_books

      if @order.save
        redirect_to(controller: :orders, action: :delivery_info, total: @order.total.to_f)
      else
        redirect_to(controller: :orders, action: :order)
      end

    else
      redirect_to(controller: :orders, action: :order)
    end
    # TODO order params (name, address, payment etc)
  end

  # TODO rename to ordering client delivery info
  def delivery_info
    # TODO create client or find

    # TODO assigning client to order ans save

    @client = Client.new(
        name: params[:name],
        phone: params[:phone],
        address: params[:address],
        delivery_id: params[:delivery_id],
        payment_id: params[:payment_id],
        notes: params[:notes],
        email: params[:email]
    )
    @order_total = params[:total]
  end

  # TODO rename to order
  def make_order
    @order = Order.find_by_session session.id

    @client = @order.build_client(
        name: params[:client][:name],
        phone: params[:client][:phone],
        address: params[:client][:address],
        delivery_id: params[:client][:delivery_id],
        payment_id: params[:client][:payment_id],
        notes: params[:client][:notes],
        email: params[:client][:email]
    )

    if @order.save
      redirect_to(controller: :orders, action: :thank_you)
    else
      redirect_to(controller: :orders, action: :delivery_info, params: params[:client])
    end
  end

  def thank_you
    @order = Order.find_by_session session.id
    session[:cart] = []
    # TODO order complete
  end

  private

  def order_books
    Book.where(id: session[:cart].map { |id, _| id }).map { |book| {book: book, qty: session[:cart][book.id.to_s]} }
  end

end

app/views/control_panel/orders/_books_list.haml
%table.stripped
  %thead
    %tr
      %th Name
      %th Qty
      %th Price
      %th Total

  %tbody
    - total = 0
    - @order.books.includes(:book).each do |book|
      - total += book.quantity * book.price
      %tr
        %td= book.book.name
        %td= book.quantity
        %td= book.price
        %td= book.quantity * book.price

  %tfoot
    %tr
      %th
      %th
      %th Total
      %th= total

app/views/control_panel/orders/_form.haml
- if order_form.object.errors.any?
  .col
    - order_form.object.errors.each do |error, text|
      %p.red-text= "#{error} - #{text}!"

.col.s12.l6
  .input-field
    %i.material-icons.prefix reorder
    = order_form.collection_select :status_id, OrderStatus.all, :id, :name
    = order_form.label :status_id, 'Status', class: 'icon_prefix'

.col.s12.l6
  = render 'form_books', order_form: order_form

:javascript
  $(document).ready(function() {
    $('select').material_select();
    Materialize.updateTextFields();
  });

app/views/control_panel/orders/_form_books.haml
%table.stripped#order_books
  %thead
    %tr
      %th X
      %th Name
      %th Price
      %th Qty
      %th Total

  %tbody
    = order_form.fields_for :books do |book_form|
      = render 'order_book', book_form: book_form

= link_to '#', class: 'duplicate_nested_form btn-floating btn-large waves-effect waves-light red' do
  %i.material-icons add

app/views/control_panel/orders/_info.haml
%p created #{@order.created_at}
%p updated #{@order.updated_at}
%p status #{@order.status}

app/views/control_panel/orders/_order_book.haml
%tr.duplicatable_nested_form
  %td
    = link_to 'R', '', remote: true, class: 'destroy_duplicate_nested_form'
    - if book_form.object.persisted?
      = book_form.hidden_field(:_destroy, class: '_destroy')

  %td= book_form.select :book_id, options_for_select(Book.all.map{ |book| [book.name, book.id, {data: {price: book.price}}] }, selected_key = book_form.object.book_id), { include_blank: '' }, onchange: 'reloadPrice(this)'
  %td= book_form.text_field :price, class: 'order_book-price', onchange: 'recalculateTotal(this)'
  %td= book_form.text_field :quantity, input_html: { min: 1 }, class: 'order_book-qty', onchange: 'recalculateTotal(this)'
  %td
    - if book_form.object.quantity && book_form.object.price
      %strong.order_book-total= book_form.object.quantity * book_form.object.price

-# TODO do not use price in options attr without check

:coffeescript

  @reloadPrice = (_this)->
    book = $(_this).parent().parent().parent()
    price = $(_this).find('option:selected').attr('data-price')
    @bookTotalPrice(book, price)
    return

  @recalculateTotal = (_this)->
    book = $(_this).parent().parent()
    price = book.find('.order_book-price').val()
    @bookTotalPrice(book, price)
    return

  @bookTotalPrice = (book, price) ->
    qty = book.find('.order_book-qty').val()
    book.find('.order_book-price').val(price)
    book.find('.order_book-total').html(price * qty)
    return

app/views/control_panel/orders/edit.haml
.row
  .col.s12
    %h3 Редактировать заказ

= form_for @order, url: cp_order_path(@order), id: 'order_form' do |order_form|
  .row
    = render 'form', order_form: order_form

  .row
    .col
      = order_form.submit class: 'btn waves-effect waves-light'

app/views/control_panel/orders/index.haml
.row
  .col.s12.m6.l4
    = render '/control_panel/shared/tile', link: new_cp_order_path, title: '+', text: 'Добавить'
  .col.s12.m6.l4
    = render '/control_panel/shared/tile', link: '', title: 11, text: 'Новый'
  .col.s12.m6.l4
    = render '/control_panel/shared/tile', link: '', title: @orders_count[:all], text: 'Всего'

.row
  .col.s12
    - if @orders.any?
      %table.striped
        %thead
          %tr
            %th{data: {field: 'id'}} #
            %th{data: {field: 'date'}} Дата
            -#%th{data: {field: 'client'}} Клиент
            %th{data: {field: 'status'}} Статус
            %th{data: {field: 'sum'}} Сумма
            %th{data: {field: 'action'}} Действие
        %tbody
          - @orders.each do |order|
            %tr
              %td= order.id
              %td= order.created_at
              -#%td -
              %td= order.status
              %td= order.total
              %td
                = link_to cp_order_path(order) do
                  %i.material-icons.small visibility
                = link_to edit_cp_order_path(order) do
                  %i.material-icons.small edit

app/views/control_panel/orders/new.haml
.row
  .col.s12
    %h3 Добавить новый заказ

= form_for @order, url: cp_orders_path, id: 'order_form' do |order_form|
  .row
    = render 'form', order_form: order_form

  .row
    .col
      = order_form.submit class: 'btn waves-effect waves-light'

app/views/control_panel/orders/show.haml
.row
  .col.s12
    %h3 Информация по заказу №: #{@order.id}

.row
  .col.s12.l6
    = render 'info'

  .col.s12.l6
    = render 'books_list'

= link_to 'edit', edit_cp_order_path(@order), class: 'btn waves-effect waves-light'